import{a as d,S as y,i as a}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const h="49733836-ef97dcade25b1489c7fb046c8";async function p(s){return(await d.get("https://pixabay.com/api/",{params:{key:h,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),u=document.querySelector(".loader"),b=new y(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const o=s.map(({largeImageURL:t,webformatURL:l,tags:e,likes:r,views:i,comments:g,downloads:m})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${t}">
            <img class="gallery-image" src="${l}" alt="${e}" width="360" height="152" />
          </a>
          <ul class="gallery-info">
            <li class="gallery-info-item"><b>Likes</b> ${r}</li>
            <li class="gallery-info-item"><b>Views</b> ${i}</li>
            <li class="gallery-info-item"><b>Comments</b> ${g}</li>
            <li class="gallery-info-item"><b>Downloads</b> ${m}</li>
          </ul>
        </li>
      `).join("");f.innerHTML=o,b.refresh()}function C(){f.innerHTML=""}function w(){u.classList.remove("is-hidden")}function q(){u.classList.add("is-hidden")}const n="/goit-js-hw-11/assets/error-COYrvVuo.svg",c=document.querySelector(".form");c.addEventListener("submit",s=>{s.preventDefault();const o=s.target.elements["search-text"].value.trim().toLowerCase();if(o===""){a.error({message:"Please enter a search query.",position:"topRight",backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff",class:"error-icon",iconUrl:n});return}C(),w(),p(o).then(t=>{if(t.hits.length===0){a.error({message:"Sorry, there are no images matching<br/> your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff",class:"error-icon",iconUrl:n});return}L(t.hits),c.reset()}).catch(t=>{a.error({message:"Something went wrong. Please try again later!",position:"topRight",backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff",class:"error-icon",iconUrl:n}),console.log("Fetch error:",t)}).finally(()=>{q()})});
//# sourceMappingURL=index.js.map
